// Handles AI card generation logic in the Use Case layer.
// Uses GeminiApiClient
// Archie
package use_case.studyDeck.DeckManagement;

import entity.DeckManagement.StudyCard;
import frameworks_and_drivers.AIServices.GeminiApiClient;
import java.util.ArrayList;

public class CardGenerator {

    private final GeminiApiClient geminiApiClient;
    private final String apiKey = "404";

    // Constructor to init CardGenerator with a GeminiApiClient instance.
    // @param apiKey The API key for the Gemini service.
    public CardGenerator(String apiKey) {
        this.geminiApiClient = new GeminiApiClient(apiKey);
    }

    // TODO Generate a new StudyCard using AI with the specified topic and source text.
    // @param topic The topic for the generated card.
    // @param sourceText The source text to base the card on.
    // @return A new StudyCard object generated by AI, or null if generation fails.
    public StudyCard generateCard(String topic, String sourceText) {
        throw new UnsupportedOperationException("Method not yet implemented");
    }

    // TODO Generate multiple StudyCards using AI with the specified topic and source text.
    // @param topic The topic for the generated cards.
    // @param sourceText The source text to base the cards on.
    // @param numberOfCards The number of cards to generate.
    // @return A list of StudyCard objects generated by AI.
    public ArrayList<StudyCard> generateMultipleCards(String topic, String sourceText, int numberOfCards) {
        throw new UnsupportedOperationException("Method not yet implemented");
    }

    // TODO Validate that the AI-generated response contains all required card elements.
    // @param aiResponse The raw response from the AI service.
    // @return True if the response contains valid card elements, false otherwise.
    private boolean validateAIResponse(String aiResponse) {
        throw new UnsupportedOperationException("Method not yet implemented");
    }

    // TODO Parse the AI response into a StudyCard object.
    // @param aiResponse The raw response from the AI service.
    // @return A StudyCard object parsed from the AI response, or null if parsing fails.
    private StudyCard parseAIResponseToCard(String aiResponse) {
        throw new UnsupportedOperationException("Method not yet implemented");
    }

    // TODO Format the prompt sent to the AI service to ensure proper card structure.
    // @param topic The topic for the generated card.
    // @param sourceText The source text to base the card on.
    // @return A properly formatted prompt string for the AI service.
    private String formatAIPrompt(String topic, String sourceText) {
        throw new UnsupportedOperationException("Method not yet implemented");
    }

    // TODO Sanitize the AI response to remove any unwanted formatting or text.
    // @param rawResponse The raw response from the AI service.
    // @return A sanitized response string ready for parsing.
    private String sanitizeAIResponse(String rawResponse) {
        throw new UnsupportedOperationException("Method not yet implemented");
    }
}